title: "LLMs for Historical Text Analysis"
description: "Exploring the use of LLMs in Digital Humanities"
baseurl: ""
url: "https://pahaul.github.io"
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
