title: "LLMs for Automated Text Analysis in the Digital Humanities"
description: "Exploring Their Strengths, Limitations, and Practical Value"
baseurl: ""
url: "https://pahaul.github.io"
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 
